# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

User.create(username: "Anthony", password: "password")
User.create(username: "Ben", password: "password")
User.create(username: "Carl", password: "password")
User.create(username: "David", password: "password")
User.create(username: "Edward", password: "password")
User.create(username: "Frank", password: "password")
User.create(username: "Gavin", password: "password")
User.create(username: "Henry", password: "password")
User.create(username: "Ian", password: "password")
User.create(username: "John", password: "password")
User.create(username: "Kevin", password: "password")
User.create(username: "Lewis", password: "password")
User.create(username: "Mark", password: "password")
User.create(username: "Nick", password: "password")
User.create(username: "Owen", password: "password")
User.create(username: "Peter", password: "password")
User.create(username: "Quentin", password: "password")
User.create(username: "Robin", password: "password")
User.create(username: "Simon", password: "password")
User.create(username: "Tim", password: "password")
User.create(username: "Ursula", password: "password")
User.create(username: "Victor", password: "password")
User.create(username: "William", password: "password")
User.create(username: "Xavier", password: "password")
User.create(username: "Yusaf", password: "password")
User.create(username: "Zack", password: "password")

Message.create(body: "Message 1", user_id: 1)
Message.create(body: "Message 2", user_id: 2)
Message.create(body: "Message 3", user_id: 3)
Message.create(body: "Message 4", user_id: 7)
Message.create(body: "Message 5", user_id: 4)
Message.create(body: "Message 6", user_id: 9)
Message.create(body: "Message 7", user_id: 3)
Message.create(body: "Message 8", user_id: 5)
Message.create(body: "Message 9", user_id: 12)
Message.create(body: "Message 10", user_id: 24)
Message.create(body: "Message 11", user_id: 3)
Message.create(body: "Message 12", user_id: 1)